---
- name: Reload nginx
  service:
    name: "nginx"
    state: reloaded

- name: Start nginx
  service:
    name: "nginx"
    state: started

- name: Kill pid
  shell: 'kill -HUP $(cat /var/run/nginx.pid)'

- name: Update ca-certificates
  shell: update-ca-certificates